config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:list_id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Create New Bookmark</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <h1>My To-Watch Lists</h1>
</div>

<div>
  <button class="btn-ghost">
    <i class="fa-solid fa-plus"></i> <%= link_to 'New List', new_list_path %>
  </button>
</div>

<div class="card-container">
  <% @lists.each do |list| %>
    <div class="card" style="width: 18rem;">
      <img src="https://thereader.mitpress.mit.edu/wp-content/uploads/2020/01/lede-1-700x420.jpg" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.name, list%></h5>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create New List</h1>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save List", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<div>
  <button class="btn-ghost">
 <i class="fa-solid fa-arrow-left"></i> <%= link_to 'back to Lists', lists_path %>
  </button>
</div>

<div class="banner">
  <h1> <%= @list.name %> </h1>
</div>

<div>
  <button class="btn-ghost">
    <i class="fa-solid fa-plus"></i> <%= link_to "New Bookmark", new_list_bookmark_path(@list) %>
  </button>
</div>

<div class="card-container">
  <% @bookmarks.each do |bookmark| %>
    <div class="card" style="width: 18rem;">
      <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p class="card-text"><em>"<%= bookmark.movie.overview %>"</em></p>
        <p class="card-text"><i class="fa-regular fa-comment"></i>: "<%= bookmark.comment %>"</p>
        <i class="fa-solid fa-trash"></i> <%= link_to "Delete",  list_bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
  <% end %>
</div>